plugins {
    id 'com.android.application'
}

android {
    namespace 'com.thanuja.thanuboard' // ඔයාගේ ඇප් එකේ package name එක මෙතනට දාන්න
    compileSdk 34

    defaultConfig {
        applicationId "com.thanuja.thanuboard"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    
    // ⚠️ අර ඉස්සෙල්ලා error එක ආපු පරණ module(...) කෑල්ල වෙනුවට සාමාන්‍ය විදිහට dependency එක මෙහෙම දාන්න:
    // implementation 'group:artifact:version' 
}
